# Generated by Django 2.1.3 on 2018-11-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('core', '0002_auto_20181108_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='plan',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='Region'),
        ),
    ]
