# Generated by Django 2.1.3 on 2018-11-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181130_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='city',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='region',
        ),
        migrations.AddField(
            model_name='analyze',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Neighborhood'),
        ),
    ]
