# Generated by Django 2.1.3 on 2018-11-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181130_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Lot'),
        ),
    ]
