# Generated by Django 2.1.3 on 2018-11-30 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_analyze_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('registration_found', 'Regisration found'), ('analyzed', 'Analyzed')], default='requested', max_length=30, verbose_name='State'),
        ),
    ]
