# Generated by Django 2.1.3 on 2018-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181130_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('owner', 'Proprietário'), ('real_estate', 'Imobiliária')], default='owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
    ]
