# Generated by Django 2.1.3 on 2019-01-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_report_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Registration Number'),
        ),
    ]
