# Generated by Django 2.1.3 on 2019-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190127_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='default_observation',
        ),
        migrations.AddField(
            model_name='indicator',
            name='observation_not_ok',
            field=models.TextField(null=True, verbose_name='Not Ok Observation'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='observation_ok',
            field=models.TextField(null=True, verbose_name='Ok Observation'),
        ),
    ]
