# Generated by Django 2.1.3 on 2019-01-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190127_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='observation_not_ok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Not Ok Observation'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='observation_ok',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ok Observation'),
        ),
    ]
