# Generated by Django 2.1.3 on 2019-01-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190128_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=20, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('registration_found', 'Regisration found'), ('analyzed', 'Perished')], default='requested', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
