# Generated by Django 2.1.3 on 2019-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190128_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('not_ok', 'Not Ok'), ('not_analyzed', 'Not Analyzed')], max_length=30, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
