# Generated by Django 2.1.3 on 2019-01-30 17:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190130_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='request_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('52.90'), max_digits=20, verbose_name='Credit used'),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, choices=[('ok', 'Ok'), ('not_ok', 'Not Ok')], max_length=30, null=True, verbose_name='State'),
        ),
    ]
