# Generated by Django 2.1.3 on 2019-02-06 14:19

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190130_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iugu_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Iugu Credit Card Data'),
        ),
        migrations.AlterField(
            model_name='account',
            name='request_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('52.90'), max_digits=20, verbose_name='Request price'),
        ),
    ]
