# Generated by Django 2.1.3 on 2019-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190206_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=255, null=True, verbose_name='Número do seu Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP do seu Endereço'),
        ),
    ]
