# Generated by Django 2.1.3 on 2019-02-06 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190206_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
