# Generated by Django 2.1.3 on 2019-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_charge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
