# Generated by Django 2.1.3 on 2019-02-22 19:10

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190206_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_download_registration',
            field=models.BooleanField(default=False, verbose_name='Pode fazer download da matrícula'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='Credit available for new requests'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_used',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), max_digits=20, verbose_name='Credit used'),
        ),
        migrations.AlterField(
            model_name='account',
            name='iugu_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Iugu Credit Card Data'),
        ),
        migrations.AlterField(
            model_name='account',
            name='request_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('52.90'), max_digits=20, verbose_name='Request price'),
        ),
        migrations.AlterField(
            model_name='account',
            name='requests',
            field=models.IntegerField(blank=True, default=0, verbose_name='Requests available for free'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('owner', 'Pessoa Física'), ('company', 'Pessoa Jurídica'), ('real_estate', 'Imobiliária'), ('self_employed_broker', 'Corretor Autônomo'), ('Lawyer', 'Advogado')], default='owner', max_length=20, verbose_name='Qual o seu perfil?'),
        ),
    ]
