# Generated by Django 2.1.3 on 2019-02-22 19:20

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190222_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='registration',
            field=models.FileField(null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='test_bucket'), upload_to='', verbose_name='Registration'),
        ),
    ]
